import type { Metadata } from 'next';
import { Lexend_Deca } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import Footer from './components/Footer';

const lexendDeca = Lexend_Deca({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${lexendDeca.className} antialiased`}>
				<Header></Header>
				{children}
				<Footer></Footer>
			</body>
		</html>
	);
}
